import { initializeApp } from "firebase/app"
import { getFirestore, collection, addDoc } from "firebase/firestore"

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const dummyHotels = [
  {
    name: "The Spice Garden Resort",
    location: "Goa, India",
    city: "Goa",
    country: "India",
    rating: 4.5,
    pricePerNight: 8500,
    currency: "INR",
    description: "Luxury beachfront resort with authentic Goan cuisine and spice gardens",
    amenities: ["Beach Access", "Spa", "Pool", "Restaurant", "WiFi", "Gym"],
    foodSpecialties: [
      "Goan Fish Curry",
      "Bebinca (Traditional Dessert)",
      "Prawn Balchão",
      "Chicken Cafreal",
      "Feni Cocktails",
    ],
    cuisine: ["Goan", "Seafood", "Portuguese", "Indian"],
    images: ["/luxury-beach-resort-goa.jpg"],
    coordinates: { lat: 15.2993, lng: 74.124 },
    checkInTime: "15:00",
    checkOutTime: "11:00",
    totalRooms: 120,
    availableRooms: 45,
  },
  {
    name: "Himalayan Heritage Hotel",
    location: "Manali, Himachal Pradesh",
    city: "Manali",
    country: "India",
    rating: 4.2,
    pricePerNight: 6500,
    currency: "INR",
    description: "Mountain retreat offering traditional Himachali cuisine with valley views",
    amenities: ["Mountain View", "Restaurant", "Bonfire", "WiFi", "Parking", "Room Service"],
    foodSpecialties: ["Dham (Traditional Feast)", "Chana Madra", "Siddu (Steamed Bread)", "Trout Fish", "Apple Wine"],
    cuisine: ["Himachali", "North Indian", "Tibetan", "Continental"],
    images: ["/mountain-hotel-manali-himachal.jpg"],
    coordinates: { lat: 32.2396, lng: 77.1887 },
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 80,
    availableRooms: 22,
  },
  {
    name: "Royal Rajasthani Palace",
    location: "Jaipur, Rajasthan",
    city: "Jaipur",
    country: "India",
    rating: 4.8,
    pricePerNight: 12000,
    currency: "INR",
    description: "Heritage palace hotel serving authentic Rajasthani royal cuisine",
    amenities: ["Heritage Architecture", "Royal Dining", "Spa", "Pool", "Cultural Shows", "WiFi"],
    foodSpecialties: ["Dal Baati Churma", "Laal Maas", "Gatte ki Sabzi", "Ker Sangri", "Rajasthani Thali"],
    cuisine: ["Rajasthani", "Marwari", "North Indian", "Mughlai"],
    images: ["/rajasthani-palace-hotel-jaipur.jpg"],
    coordinates: { lat: 26.9124, lng: 75.7873 },
    checkInTime: "15:00",
    checkOutTime: "11:00",
    totalRooms: 150,
    availableRooms: 67,
  },
  {
    name: "Backwater Bliss Resort",
    location: "Alleppey, Kerala",
    city: "Alleppey",
    country: "India",
    rating: 4.6,
    pricePerNight: 9500,
    currency: "INR",
    description: "Waterfront resort specializing in Kerala's traditional cuisine and Ayurveda",
    amenities: ["Backwater View", "Ayurvedic Spa", "Houseboat Tours", "Restaurant", "WiFi", "Yoga"],
    foodSpecialties: [
      "Kerala Fish Curry",
      "Appam with Stew",
      "Puttu and Kadala",
      "Banana Leaf Meals",
      "Coconut-based Desserts",
    ],
    cuisine: ["Kerala", "South Indian", "Seafood", "Ayurvedic"],
    images: ["/kerala-backwater-resort-alleppey.jpg"],
    coordinates: { lat: 9.4981, lng: 76.3388 },
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 95,
    availableRooms: 31,
  },
  {
    name: "Desert Oasis Hotel",
    location: "Jaisalmer, Rajasthan",
    city: "Jaisalmer",
    country: "India",
    rating: 4.3,
    pricePerNight: 7500,
    currency: "INR",
    description: "Desert hotel offering traditional Rajasthani cuisine with camel safari experiences",
    amenities: ["Desert View", "Camel Safari", "Cultural Programs", "Restaurant", "WiFi", "Rooftop Dining"],
    foodSpecialties: ["Pyaaz Kachori", "Mirchi Bada", "Desert Mutton Curry", "Bajre ki Roti", "Mawa Kachori"],
    cuisine: ["Rajasthani", "Desert Cuisine", "North Indian", "Vegetarian"],
    images: ["/desert-hotel-jaisalmer-rajasthan.jpg"],
    coordinates: { lat: 26.9157, lng: 70.9083 },
    checkInTime: "15:00",
    checkOutTime: "11:00",
    totalRooms: 70,
    availableRooms: 18,
  },
  {
    name: "Tea Garden Retreat",
    location: "Darjeeling, West Bengal",
    city: "Darjeeling",
    country: "India",
    rating: 4.4,
    pricePerNight: 5500,
    currency: "INR",
    description: "Hill station hotel surrounded by tea gardens, serving Bengali and Nepali cuisine",
    amenities: ["Tea Garden View", "Tea Tasting", "Mountain View", "Restaurant", "WiFi", "Library"],
    foodSpecialties: [
      "Momos (Tibetan Dumplings)",
      "Thukpa (Noodle Soup)",
      "Bengali Fish Curry",
      "Darjeeling Tea",
      "Gundruk (Fermented Greens)",
    ],
    cuisine: ["Bengali", "Nepali", "Tibetan", "North Indian"],
    images: ["/tea-garden-hotel-darjeeling.jpg"],
    coordinates: { lat: 27.036, lng: 88.2627 },
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 60,
    availableRooms: 25,
  },
  {
    name: "Coastal Paradise Resort",
    location: "Kovalam, Kerala",
    city: "Kovalam",
    country: "India",
    rating: 4.7,
    pricePerNight: 11000,
    currency: "INR",
    description: "Beachfront luxury resort with fresh seafood and traditional Kerala cuisine",
    amenities: ["Beach Access", "Infinity Pool", "Spa", "Multiple Restaurants", "WiFi", "Water Sports"],
    foodSpecialties: [
      "Karimeen Fish Fry",
      "Prawn Moilee",
      "Coconut Rice",
      "Payasam (Sweet Pudding)",
      "Fresh Coconut Water",
    ],
    cuisine: ["Kerala", "Seafood", "South Indian", "Continental"],
    images: ["/beach-resort-kovalam-kerala.jpg"],
    coordinates: { lat: 8.4004, lng: 76.9784 },
    checkInTime: "15:00",
    checkOutTime: "11:00",
    totalRooms: 140,
    availableRooms: 52,
  },
  {
    name: "Valley View Lodge",
    location: "Shimla, Himachal Pradesh",
    city: "Shimla",
    country: "India",
    rating: 4.1,
    pricePerNight: 4500,
    currency: "INR",
    description: "Colonial-style hotel offering British-Indian fusion cuisine with mountain views",
    amenities: ["Valley View", "Heritage Building", "Restaurant", "WiFi", "Parking", "Room Heater"],
    foodSpecialties: ["Himachali Dham", "Chana Madra", "British-style Tea", "Apple Pie", "Mutton Curry"],
    cuisine: ["Himachali", "North Indian", "Continental", "British"],
    images: ["/colonial-hotel-shimla-himachal.jpg"],
    coordinates: { lat: 31.1048, lng: 77.1734 },
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 50,
    availableRooms: 15,
  },
]

async function seedHotels() {
  console.log("Starting to seed hotels data...")

  try {
    for (const hotel of dummyHotels) {
      const docRef = await addDoc(collection(db, "hotels"), {
        ...hotel,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      console.log(`Added hotel: ${hotel.name} with ID: ${docRef.id}`)
    }

    console.log("Successfully seeded all hotels!")
  } catch (error) {
    console.error("Error seeding hotels:", error)
  }
}

seedHotels()
